apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app: {{ include "my-chart.name" . }}
    chart: {{ include "my-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internallPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ include "my-chart.name" . }}
    release: {{ .Release.Name }}
